### ISSUE TITLE
冒昧询问一下

### ISSUE THREAD

**Issue by Tinhone** [xingchuanzhen/Minecraft_Bypass_the_program#8]
![图片](https://user-images.githubusercontent.com/81268244/167256417-03f30a7c-1392-4936-b20c-5f1f641e42c2.png)
使用程序开启后，一直在这样加载...CPU占用一度达到了70%，但是不使用程序就不会出现这种情况
想问一下这种情况会有可能是程序造成的吗，感谢

客户端版本是1.18.3104.0，可用内存充足，网络正常

**Comment by xingchuanzhen** [comment]
您或许可以重启系统来尝试解决此问题

**Comment by xingchuanzhen** [comment]
经过我的测试似乎并没有出现您描述的情况
![Snipaste_2022-05-08_12-11-37](https://user-images.githubusercontent.com/78350684/167281399-ee1573c1-e1ea-4fcd-8406-0a0c56eaf39e.png)

**Comment by Tinhone** [comment]
感谢您的解答。经过数次排查，发现是加载资源包时出现的问题，十分抱歉这几天给您添麻烦了，对不起🙇‍♂️
